In [32]:
import pandas as pd 
import numpy as np

In [33]:
df=pd.read_csv("employee_sample_dataset.csv")

In [34]:
df.head(30)

,EmployeeID,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating
0,85.0,Sara Ali,50.0,peshawar,Finance,37654.70,2022-04-03,sara.ali@example.com,2.1
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,299.0,Ali Javed,32.0,multan,HR,96309.61,11-Jul-2020,ALI.JAVED@EXAMPLE.COM,4.8
3,288.0,Noor Raza,28.0,Pindi,Finance,87658.83,25/03/2022,noor.raza@example.com,3.0
4,100.0,Ali Shah,16.0,peshawar,Marketing,48996.14,10-15-2021,ali.shah@example.com,3.5
5,276.0,Faisal Raza,42.0,Pindi,Engineering,57324.44,03-29-2022,faisal.raza@example.com,2.2
6,142.0,Zara Butt,40.0,LAHORE,Marketing,38797.37,16/02/2021,zara.butt@example.com,1.3
7,119.0,Omar Ansari,34.0,islamabad,Support,72397.14,16/12/2022,omar.ansari@example.com,4.8
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,31.0,Ayesha Baig,25.0,islamabad,HR,64964.86,13-Jan-2023,ayesha.baig@example.com,4.7
10,123.0,Tariq Chaudhry,31.0,Faisalabad,HR,NaN,2021-08-25,tariq.chaudhry@example.com,1.2
11,67.0,Noor Shah,24.0,Islamabad,Finance,58683.79,07-18-2021,noor.shah@example.com,4.9
12,284.0,Tariq Farooq,17.0,Isl'abad,Support,97882.70,27/06/2020,tariq.farooq@example.com,1.4
13,171.0,Tariq Farooq,27.0,rawalpindi,Finance,59142.54,11-23-2022,tariq.farooq@example.com,1.7
14,75.0,Bilal Malik,33.0,Karachi,Sales,82706.35,02-24-2022,bilal.malik@example.com,3.3
15,273.0,Usman Dar,17.0,Lahore,Marketing,49408.46,14-Sep-2021,usman.dar@example.com,3.1
16,71.0,Ahmed Butt,23.0,LAHORE,Sales,84649.45,2021-05-12,ahmed.butt@example.com,4.8
17,139.0,Danish Siddiqui,49.0,KARACHI,finance,59653.05,30/05/2019,danish.siddiqui@example.com,3.3
18,218.0,Ali Malik,23.0,Multan,Marketing,58659.97,19/10/2022,NaN,4.0
19,300.0,Fatima Shah,41.0,multan,Sales,3066568.00,01-Dec-2020,fatima.shah@example.com,2.6
20,164.0,Danish Dar,39.0,Isl'abad,Marketing,81614.01,05-03-2020,danish.dar@example.com,4.8
21,255.0,Bilal Shah,37.0,Isl'abad,Marketing,83885.27,2021-05-18,bilal.shah@example.com,4.3
22,189.0,Sara Butt,20.0,Multan,Engineering,86259.38,2023-03-12,sara.butt@example.com,1.4
23,177.0,Usman Ansari,29.0,Quetta,HR,28961.58,05-29-2021,usman.ansari@example.com,3.5
24,149.0,Fatima Awan,19.0,FSD,Support,63012.50,2022-11-12,fatima.awan@example.com,1.2
25,160.0,Hina Khan,28.0,Quetta,Support,68153.83,09-30-2020,hina.khan@example.com,1.1
26,58.0,Danish Shah,42.0,Quetta,HR,57657.08,06-26-2020,danish.shah@example.com,4.6
27,95.0,Amna Mirza,46.0,Rawalpindi,Support,83099.63,2021-07-25,amna.mirza@example.com,11.5
28,38.0,Ayesha Iqbal,28.0,Multan,HR,69217.26,04/01/2023,ayesha.iqbal@example.com,2.4
29,98.0,Omar Butt,30.0,LAHORE,HR,112440.11,07/09/2021,omar.butt@example.com,1.4

Check the duplicate row

In [35]:
df[df.duplicated()]

,EmployeeID,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,177.0,Usman Ansari,29.0,Quetta,HR,28961.58,05-29-2021,usman.ansari@example.com,3.5
90,74.0,Iqra Raza,24.0,rawalpindi,Support,64740.69,05-24-2021,iqra.raza@example.com,3.2
94,123.0,Tariq Chaudhry,31.0,Faisalabad,HR,NaN,2021-08-25,tariq.chaudhry@example.com,1.2
107,300.0,Fatima Shah,41.0,multan,Sales,3066568.00,01-Dec-2020,fatima.shah@example.com,2.6
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,267.0,Omar Shah,33.0,multan,Finance,71320.33,2023-09-08,omar.shah@example.com,4.9
189,214.0,Faisal Ali,NaN,rawalpindi,engineering,76912.41,08-02-2023,faisal.ali@example.com,3.5
190,128.0,Omar Javed,36.0,LAHORE,Engineering,92450.83,11-06-2022,omar.javed@example.com,1.3
196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,107.0,Bilal Javed,30.0,Pindi,Sales,86766.34,2020-10-11,bilal.javed@example.com,4.8
244,243.0,Ali Dar,32.0,Faisalabad,Marketing,74517.50,09-Aug-2019,ali.dar@example.com,1.8
268,59.0,Iqra Qureshi,NaN,peshawar,Engineering,81928.96,2023-03-10,iqra.qureshi@example.com,3.6
269,124.0,Fatima Ansari,15.0,quetta,Sales,110408.63,03/07/2019,fatima.ansari@example.com,4.6
274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,148.0,Ali Ali,34.0,KARACHI,engineering,NaN,29/02/2020,ali.ali@example.com,2.9
295,190.0,Tariq Awan,28.0,Lahore,HR,62480.14,02-15-2023,tariq.awan@example.com,1.6
302,276.0,Faisal Raza,42.0,Pindi,Engineering,57324.44,03-29-2022,faisal.raza@example.com,2.2
313,186.0,Bilal Awan,50.0,Peshawar,Sales,95290.65,22-May-2019,bilal.awan@example.com,4.0

In [36]:
df=df.drop_duplicates()

In [37]:
df[df.duplicated()]

Empty DataFrame
Columns: [EmployeeID, Name, Age, City, Department, Salary, JoinDate, Email, PerformanceRating]
Index: []

In [38]:
df.info()

<class 'pandas.DataFrame'>
Index: 301 entries, 0 to 319
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         300 non-null    float64
 1   Name               300 non-null    str
 2   Age                279 non-null    float64
 3   City               300 non-null    str
 4   Department         300 non-null    str
 5   Salary             282 non-null    float64
 6   JoinDate           292 non-null    str
 7   Email              295 non-null    str
 8   PerformanceRating  300 non-null    float64
dtypes: float64(4), str(5)
memory usage: 23.5 KB

In [39]:
df

,EmployeeID,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating
0,85.0,Sara Ali,50.0,peshawar,Finance,37654.70,2022-04-03,sara.ali@example.com,2.1
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,299.0,Ali Javed,32.0,multan,HR,96309.61,11-Jul-2020,ALI.JAVED@EXAMPLE.COM,4.8
3,288.0,Noor Raza,28.0,Pindi,Finance,87658.83,25/03/2022,noor.raza@example.com,3.0
4,100.0,Ali Shah,16.0,peshawar,Marketing,48996.14,10-15-2021,ali.shah@example.com,3.5
...,...,...,...,...,...,...,...,...,...
315,212.0,Omar Malik,40.0,karachi,Sales,58129.10,30-Jun-2022,omar.malik@example.com,3.0
316,68.0,Usman Ansari,39.0,karachi,Marketing,70208.11,30/04/2024,usman.ansari@example.com,3.5
317,26.0,Faisal Awan,43.0,faisalabad,Support,81763.63,28/02/2023,faisal.awan@example.com,3.0
318,197.0,Omar Qureshi,999.0,Multan,Sales,86411.97,08-24-2021,omar.qureshi@example.com,2.3
319,176.0,Hina Javed,26.0,islamabad,Marketing,86590.09,2022-02-27,hina.javed@example.com,1.8

In [40]:
df[df['EmployeeID']==1000]

Empty DataFrame
Columns: [EmployeeID, Name, Age, City, Department, Salary, JoinDate, Email, PerformanceRating]
Index: []

In [41]:
df['EmployeeID'].max()

np.float64(300.0)

In [42]:
next_id = int(df['EmployeeID'].max()) + 1

for idx in df[df['EmployeeID'].isna()].index:
    df.loc[idx, 'EmployeeID'] = next_id
    next_id += 1

Sussessfully mange the thr null and duplicate value

In [43]:
df['EmployeeID']=df['EmployeeID'].astype(int)

In [44]:
print(type(df))

<class 'pandas.DataFrame'>

In [46]:
df=df.set_index('EmployeeID')

In [47]:
df

,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating
EmployeeID,,,,,,,,
85,Sara Ali,50.0,peshawar,Finance,37654.70,2022-04-03,sara.ali@example.com,2.1
301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,Ali Javed,32.0,multan,HR,96309.61,11-Jul-2020,ALI.JAVED@EXAMPLE.COM,4.8
288,Noor Raza,28.0,Pindi,Finance,87658.83,25/03/2022,noor.raza@example.com,3.0
100,Ali Shah,16.0,peshawar,Marketing,48996.14,10-15-2021,ali.shah@example.com,3.5
...,...,...,...,...,...,...,...,...
212,Omar Malik,40.0,karachi,Sales,58129.10,30-Jun-2022,omar.malik@example.com,3.0
68,Usman Ansari,39.0,karachi,Marketing,70208.11,30/04/2024,usman.ansari@example.com,3.5
26,Faisal Awan,43.0,faisalabad,Support,81763.63,28/02/2023,faisal.awan@example.com,3.0
197,Omar Qureshi,999.0,Multan,Sales,86411.97,08-24-2021,omar.qureshi@example.com,2.3
176,Hina Javed,26.0,islamabad,Marketing,86590.09,2022-02-27,hina.javed@example.com,1.8

In [48]:
df.rename(columns={'EmployeeID':'Employee_ID','JoinDate':'Join_Date','PerformanceRating':'Performance_Rating'})

,Name,Age,City,Department,Salary,Join_Date,Email,Performance_Rating
EmployeeID,,,,,,,,
85,Sara Ali,50.0,peshawar,Finance,37654.70,2022-04-03,sara.ali@example.com,2.1
301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,Ali Javed,32.0,multan,HR,96309.61,11-Jul-2020,ALI.JAVED@EXAMPLE.COM,4.8
288,Noor Raza,28.0,Pindi,Finance,87658.83,25/03/2022,noor.raza@example.com,3.0
100,Ali Shah,16.0,peshawar,Marketing,48996.14,10-15-2021,ali.shah@example.com,3.5
...,...,...,...,...,...,...,...,...
212,Omar Malik,40.0,karachi,Sales,58129.10,30-Jun-2022,omar.malik@example.com,3.0
68,Usman Ansari,39.0,karachi,Marketing,70208.11,30/04/2024,usman.ansari@example.com,3.5
26,Faisal Awan,43.0,faisalabad,Support,81763.63,28/02/2023,faisal.awan@example.com,3.0
197,Omar Qureshi,999.0,Multan,Sales,86411.97,08-24-2021,omar.qureshi@example.com,2.3
176,Hina Javed,26.0,islamabad,Marketing,86590.09,2022-02-27,hina.javed@example.com,1.8

In [49]:
df = df.rename_axis("Employee_ID")

In [50]:
df

,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating
Employee_ID,,,,,,,,
85,Sara Ali,50.0,peshawar,Finance,37654.70,2022-04-03,sara.ali@example.com,2.1
301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,Ali Javed,32.0,multan,HR,96309.61,11-Jul-2020,ALI.JAVED@EXAMPLE.COM,4.8
288,Noor Raza,28.0,Pindi,Finance,87658.83,25/03/2022,noor.raza@example.com,3.0
100,Ali Shah,16.0,peshawar,Marketing,48996.14,10-15-2021,ali.shah@example.com,3.5
...,...,...,...,...,...,...,...,...
212,Omar Malik,40.0,karachi,Sales,58129.10,30-Jun-2022,omar.malik@example.com,3.0
68,Usman Ansari,39.0,karachi,Marketing,70208.11,30/04/2024,usman.ansari@example.com,3.5
26,Faisal Awan,43.0,faisalabad,Support,81763.63,28/02/2023,faisal.awan@example.com,3.0
197,Omar Qureshi,999.0,Multan,Sales,86411.97,08-24-2021,omar.qureshi@example.com,2.3
176,Hina Javed,26.0,islamabad,Marketing,86590.09,2022-02-27,hina.javed@example.com,1.8

In [51]:
df = df.sort_index()

In [52]:
df

,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating
Employee_ID,,,,,,,,
1,Ayesha Khan,35.0,Multan,Sales,72234.71,2019-03-07,ayesha.khan@example.com,3.9
2,Iqra Ansari,23.0,faisalabad,Support,4068902.00,23/07/2020,iqra.ansari@example.com,1.6
3,Hina Siddiqui,44.0,Multan,Finance,90348.69,07-11-2022,hina.siddiqui@example.com,1.1
4,Mariam Malik,27.0,Faisalabad,Engineering,64496.60,2020-06-30,mariam.malik@example.com,1.7
5,Faisal Farooq,33.0,FSD,Engineering,36734.40,16/05/2019,faisal.farooq@example.com,2.7
...,...,...,...,...,...,...,...,...
297,Kamran Butt,NaN,peshawar,HR,78931.10,18-Apr-2023,kamran.butt@example.com,2.3
298,Hamza Ansari,38.0,rawalpindi,Marketing,80660.64,14/05/2021,hamza.ansari@example.com,3.5
299,Ali Javed,32.0,multan,HR,96309.61,11-Jul-2020,ALI.JAVED@EXAMPLE.COM,4.8
300,Fatima Shah,41.0,multan,Sales,3066568.00,01-Dec-2020,fatima.shah@example.com,2.6
301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
df.describe()

              Age        Salary  PerformanceRating
count  279.000000  2.820000e+02          300.00000
mean    38.426523  1.988461e+05            3.19900
std     82.873272  6.733932e+05            1.81774
min     -5.000000  2.018090e+04            1.00000
25%     26.000000  6.653740e+04            2.00000
50%     31.000000  7.895114e+04            3.00000
75%     36.000000  9.406522e+04            4.20000
max    999.000000  4.722554e+06           11.50000

In [54]:
df.info()

<class 'pandas.DataFrame'>
Index: 301 entries, 1 to 301
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               300 non-null    str
 1   Age                279 non-null    float64
 2   City               300 non-null    str
 3   Department         300 non-null    str
 4   Salary             282 non-null    float64
 5   JoinDate           292 non-null    str
 6   Email              295 non-null    str
 7   PerformanceRating  300 non-null    float64
dtypes: float64(3), str(5)
memory usage: 21.2 KB

In [55]:
df['Department'].value_counts()

Department
Finance        56
Support        55
Sales          49
HR             48
Marketing      46
Engineering    31
engineering     4
finance         4
sales           3
support         3
hr              1
Name: count, dtype: int64

In [58]:
df['Department']=df['Department'].replace({'sales':'Sales','hr':'HR','finance':'Finance','engineering':'Engineering','support':'Support'})

In [59]:
df['Department'].value_counts()

Department
Finance        60
Support        58
Sales          49
HR             49
Marketing      46
Engineering    35
Sales           3
Name: count, dtype: int64

In [60]:
df['Department']=df['Department'].replace({'Sales ':'Sales'})

In [61]:
df['Department'].value_counts()

Department
Finance        60
Support        58
Sales          52
HR             49
Marketing      46
Engineering    35
Name: count, dtype: int64

In [64]:
df['Department'].isnull().sum()

np.int64(1)

In [65]:
df['Department'] = df['Department'].fillna(df['Department'].mode()[0])

Now Successfully implmented the EDA in Department column

In [66]:
df

,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating
Employee_ID,,,,,,,,
1,Ayesha Khan,35.0,Multan,Sales,72234.71,2019-03-07,ayesha.khan@example.com,3.9
2,Iqra Ansari,23.0,faisalabad,Support,4068902.00,23/07/2020,iqra.ansari@example.com,1.6
3,Hina Siddiqui,44.0,Multan,Finance,90348.69,07-11-2022,hina.siddiqui@example.com,1.1
4,Mariam Malik,27.0,Faisalabad,Engineering,64496.60,2020-06-30,mariam.malik@example.com,1.7
5,Faisal Farooq,33.0,FSD,Engineering,36734.40,16/05/2019,faisal.farooq@example.com,2.7
...,...,...,...,...,...,...,...,...
297,Kamran Butt,NaN,peshawar,HR,78931.10,18-Apr-2023,kamran.butt@example.com,2.3
298,Hamza Ansari,38.0,rawalpindi,Marketing,80660.64,14/05/2021,hamza.ansari@example.com,3.5
299,Ali Javed,32.0,multan,HR,96309.61,11-Jul-2020,ALI.JAVED@EXAMPLE.COM,4.8
300,Fatima Shah,41.0,multan,Sales,3066568.00,01-Dec-2020,fatima.shah@example.com,2.6
301,NaN,NaN,NaN,Finance,NaN,NaN,NaN,NaN

In [67]:
df['Name'].isnull().sum()

np.int64(1)

In [68]:
df['Name'] = df['Name'].fillna(df['Name'].mode()[0])

Now Successfully implmented the EDA in Name column

In [69]:
df

,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating
Employee_ID,,,,,,,,
1,Ayesha Khan,35.0,Multan,Sales,72234.71,2019-03-07,ayesha.khan@example.com,3.9
2,Iqra Ansari,23.0,faisalabad,Support,4068902.00,23/07/2020,iqra.ansari@example.com,1.6
3,Hina Siddiqui,44.0,Multan,Finance,90348.69,07-11-2022,hina.siddiqui@example.com,1.1
4,Mariam Malik,27.0,Faisalabad,Engineering,64496.60,2020-06-30,mariam.malik@example.com,1.7
5,Faisal Farooq,33.0,FSD,Engineering,36734.40,16/05/2019,faisal.farooq@example.com,2.7
...,...,...,...,...,...,...,...,...
297,Kamran Butt,NaN,peshawar,HR,78931.10,18-Apr-2023,kamran.butt@example.com,2.3
298,Hamza Ansari,38.0,rawalpindi,Marketing,80660.64,14/05/2021,hamza.ansari@example.com,3.5
299,Ali Javed,32.0,multan,HR,96309.61,11-Jul-2020,ALI.JAVED@EXAMPLE.COM,4.8
300,Fatima Shah,41.0,multan,Sales,3066568.00,01-Dec-2020,fatima.shah@example.com,2.6
301,Sana Baig,NaN,NaN,Finance,NaN,NaN,NaN,NaN

In [72]:
df['Age']=df['Age'].fillna(df['Age'].mean())

df['Age'] = df['Age'].astype(int)

In [73]:
df

,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating
Employee_ID,,,,,,,,
1,Ayesha Khan,35,Multan,Sales,72234.71,2019-03-07,ayesha.khan@example.com,3.9
2,Iqra Ansari,23,faisalabad,Support,4068902.00,23/07/2020,iqra.ansari@example.com,1.6
3,Hina Siddiqui,44,Multan,Finance,90348.69,07-11-2022,hina.siddiqui@example.com,1.1
4,Mariam Malik,27,Faisalabad,Engineering,64496.60,2020-06-30,mariam.malik@example.com,1.7
5,Faisal Farooq,33,FSD,Engineering,36734.40,16/05/2019,faisal.farooq@example.com,2.7
...,...,...,...,...,...,...,...,...
297,Kamran Butt,38,peshawar,HR,78931.10,18-Apr-2023,kamran.butt@example.com,2.3
298,Hamza Ansari,38,rawalpindi,Marketing,80660.64,14/05/2021,hamza.ansari@example.com,3.5
299,Ali Javed,32,multan,HR,96309.61,11-Jul-2020,ALI.JAVED@EXAMPLE.COM,4.8
300,Fatima Shah,41,multan,Sales,3066568.00,01-Dec-2020,fatima.shah@example.com,2.6
301,Sana Baig,38,NaN,Finance,NaN,NaN,NaN,NaN

Successfully implmented the EDA in Age col

In [74]:
df['City'].value_counts()

City
Peshawar      25
Multan        21
Quetta        19
rawalpindi    19
peshawar      19
Pindi         17
Isl'abad      16
karachi       16
quetta        15
FSD           14
multan        14
Rawalpindi    13
Islamabad     13
faisalabad    12
islamabad     11
Faisalabad    10
lahore         9
KARACHI        9
LAHORE         9
Lahore         9
Karachi        5
Lahore         5
Name: count, dtype: int64

In [81]:
df['City']=df['City'].replace({'peshawar':'Peshawar','multan':'Multan','quetta':'Quetta','rawalpindi':'Rawalpindi','Pindi':'Rawalpindi','islamabad':'Islamabad','karachi':'Karachi','FSD':'Faisalabad','faisalabad':'Faisalabad','KARACHI':'Karachi','LAHORE':'Lahore','lahore':'Lahore'})

In [82]:
df['City'].value_counts()

City
Rawalpindi    49
Peshawar      44
Islamabad     40
Faisalabad    36
Multan        35
Quetta        34
Karachi       30
Lahore        27
Lahore         5
Name: count, dtype: int64

In [77]:
df['City'] = df['City'].replace("Isl'abad", "Islamabad")

In [78]:
df['City'].value_counts()

City
Rawalpindi    49
Peshawar      44
Islamabad     40
Faisalabad    36
Multan        35
Quetta        34
Karachi       30
Lahore        27
Lahore         5
Name: count, dtype: int64

In [83]:
df['City'] = df['City'].str.strip()

In [84]:
df['City'].value_counts()

City
Rawalpindi    49
Peshawar      44
Islamabad     40
Faisalabad    36
Multan        35
Quetta        34
Lahore        32
Karachi       30
Name: count, dtype: int64

In [85]:
df

,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating
Employee_ID,,,,,,,,
1,Ayesha Khan,35,Multan,Sales,72234.71,2019-03-07,ayesha.khan@example.com,3.9
2,Iqra Ansari,23,Faisalabad,Support,4068902.00,23/07/2020,iqra.ansari@example.com,1.6
3,Hina Siddiqui,44,Multan,Finance,90348.69,07-11-2022,hina.siddiqui@example.com,1.1
4,Mariam Malik,27,Faisalabad,Engineering,64496.60,2020-06-30,mariam.malik@example.com,1.7
5,Faisal Farooq,33,Faisalabad,Engineering,36734.40,16/05/2019,faisal.farooq@example.com,2.7
...,...,...,...,...,...,...,...,...
297,Kamran Butt,38,Peshawar,HR,78931.10,18-Apr-2023,kamran.butt@example.com,2.3
298,Hamza Ansari,38,Rawalpindi,Marketing,80660.64,14/05/2021,hamza.ansari@example.com,3.5
299,Ali Javed,32,Multan,HR,96309.61,11-Jul-2020,ALI.JAVED@EXAMPLE.COM,4.8
300,Fatima Shah,41,Multan,Sales,3066568.00,01-Dec-2020,fatima.shah@example.com,2.6
301,Sana Baig,38,NaN,Finance,NaN,NaN,NaN,NaN

Successfull implement the EDA in City column

In [86]:
df['Email'] = df['Email'].fillna(df['Email'].mode()[0])
df['JoinDate'] = df['JoinDate'].fillna(df['JoinDate'].mode()[0])

In [88]:
df=df.rename(columns={'EmployeeID':'Employee_ID','JoinDate':'Join_Date','PerformanceRating':'Performance_Rating'})

In [90]:
df

,Name,Age,City,Department,Salary,Join_Date,Email,Performance_Rating
Employee_ID,,,,,,,,
1,Ayesha Khan,35,Multan,Sales,72234.71,2019-03-07,ayesha.khan@example.com,3.9
2,Iqra Ansari,23,Faisalabad,Support,4068902.00,23/07/2020,iqra.ansari@example.com,1.6
3,Hina Siddiqui,44,Multan,Finance,90348.69,07-11-2022,hina.siddiqui@example.com,1.1
4,Mariam Malik,27,Faisalabad,Engineering,64496.60,2020-06-30,mariam.malik@example.com,1.7
5,Faisal Farooq,33,Faisalabad,Engineering,36734.40,16/05/2019,faisal.farooq@example.com,2.7
...,...,...,...,...,...,...,...,...
297,Kamran Butt,38,Peshawar,HR,78931.10,18-Apr-2023,kamran.butt@example.com,2.3
298,Hamza Ansari,38,Rawalpindi,Marketing,80660.64,14/05/2021,hamza.ansari@example.com,3.5
299,Ali Javed,32,Multan,HR,96309.61,11-Jul-2020,ALI.JAVED@EXAMPLE.COM,4.8
300,Fatima Shah,41,Multan,Sales,3066568.00,01-Dec-2020,fatima.shah@example.com,2.6
301,Sana Baig,38,NaN,Finance,NaN,05-29-2021,sana.baig@example.com,NaN

In [92]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'], format='mixed', dayfirst=True)

In [93]:
df

,Name,Age,City,Department,Salary,Join_Date,Email,Performance_Rating
Employee_ID,,,,,,,,
1,Ayesha Khan,35,Multan,Sales,72234.71,2019-07-03,ayesha.khan@example.com,3.9
2,Iqra Ansari,23,Faisalabad,Support,4068902.00,2020-07-23,iqra.ansari@example.com,1.6
3,Hina Siddiqui,44,Multan,Finance,90348.69,2022-11-07,hina.siddiqui@example.com,1.1
4,Mariam Malik,27,Faisalabad,Engineering,64496.60,2020-06-30,mariam.malik@example.com,1.7
5,Faisal Farooq,33,Faisalabad,Engineering,36734.40,2019-05-16,faisal.farooq@example.com,2.7
...,...,...,...,...,...,...,...,...
297,Kamran Butt,38,Peshawar,HR,78931.10,2023-04-18,kamran.butt@example.com,2.3
298,Hamza Ansari,38,Rawalpindi,Marketing,80660.64,2021-05-14,hamza.ansari@example.com,3.5
299,Ali Javed,32,Multan,HR,96309.61,2020-07-11,ALI.JAVED@EXAMPLE.COM,4.8
300,Fatima Shah,41,Multan,Sales,3066568.00,2020-12-01,fatima.shah@example.com,2.6
301,Sana Baig,38,NaN,Finance,NaN,2021-05-29,sana.baig@example.com,NaN

In [94]:
df['Email'].isnull().sum()

np.int64(0)

In [95]:
df['Email']=df['Email'].str.lower()

In [96]:
df

,Name,Age,City,Department,Salary,Join_Date,Email,Performance_Rating
Employee_ID,,,,,,,,
1,Ayesha Khan,35,Multan,Sales,72234.71,2019-07-03,ayesha.khan@example.com,3.9
2,Iqra Ansari,23,Faisalabad,Support,4068902.00,2020-07-23,iqra.ansari@example.com,1.6
3,Hina Siddiqui,44,Multan,Finance,90348.69,2022-11-07,hina.siddiqui@example.com,1.1
4,Mariam Malik,27,Faisalabad,Engineering,64496.60,2020-06-30,mariam.malik@example.com,1.7
5,Faisal Farooq,33,Faisalabad,Engineering,36734.40,2019-05-16,faisal.farooq@example.com,2.7
...,...,...,...,...,...,...,...,...
297,Kamran Butt,38,Peshawar,HR,78931.10,2023-04-18,kamran.butt@example.com,2.3
298,Hamza Ansari,38,Rawalpindi,Marketing,80660.64,2021-05-14,hamza.ansari@example.com,3.5
299,Ali Javed,32,Multan,HR,96309.61,2020-07-11,ali.javed@example.com,4.8
300,Fatima Shah,41,Multan,Sales,3066568.00,2020-12-01,fatima.shah@example.com,2.6
301,Sana Baig,38,NaN,Finance,NaN,2021-05-29,sana.baig@example.com,NaN

In [97]:
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

salary_outliers = df[(df['Salary'] < lower_limit) | (df['Salary'] > upper_limit)]

salary_outliers

,Name,Age,City,Department,Salary,Join_Date,Email,Performance_Rating
Employee_ID,,,,,,,,
2,Iqra Ansari,23,Faisalabad,Support,4068902.00,2020-07-23,iqra.ansari@example.com,1.6
8,Iqra Farooq,26,Peshawar,Support,4347720.50,2021-10-22,iqra.farooq@example.com,3.1
81,Hina Malik,38,Rawalpindi,Finance,152054.63,2021-04-08,hina.malik@example.com,4.2
173,Omar Ali,47,Lahore,Marketing,3785263.50,2019-01-02,omar.ali@example.com,1.2
193,Zara Shah,30,Quetta,Marketing,2842436.50,2023-08-14,zara.shah@example.com,4.9
198,Zara Farooq,34,Lahore,Marketing,20180.90,2022-04-28,zara.farooq@example.com,2.0
205,Zara Iqbal,38,Quetta,Sales,3146015.00,2019-12-15,zara.iqbal@example.com,4.8
240,Sana Baig,23,Peshawar,Sales,4266669.50,2019-01-01,sana.baig@example.com,4.8
246,Kamran Javed,43,Peshawar,Support,21812.97,2022-12-25,kamran.javed@example.com,2.8
283,Zara Chaudhry,37,Peshawar,Marketing,4722554.50,2021-03-28,zara.chaudhry@example.com,2.1
285,Ayesha Shah,31,Karachi,Sales,4370672.00,2021-01-30,ayesha.shah@example.com,1.7
300,Fatima Shah,41,Multan,Sales,3066568.00,2020-12-01,fatima.shah@example.com,2.6

In [98]:
len(salary_outliers)

12

In [99]:
df = df[(df['Salary'] >= lower_limit) & (df['Salary'] <= upper_limit)]

In [100]:
df['Salary'].isnull().sum()

np.int64(0)

In [101]:
df['Performance_Rating'].isnull().sum()

np.int64(0)

In [103]:
df.shape

(270, 8)

In [106]:
df.to_csv("Updated_Employee_Data.csv", index=False)